//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pactometro.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_en() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pactometro.Properties.Resources_en", typeof(Resources_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ABSOLUTE MAJORITY.
        /// </summary>
        public static string AbsoluteMajorityText {
            get {
                return ResourceManager.GetString("AbsoluteMajorityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add electoral process.
        /// </summary>
        public static string AddProcessText {
            get {
                return ResourceManager.GetString("AddProcessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HELP.
        /// </summary>
        public static string AidText {
            get {
                return ResourceManager.GetString("AidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear current chart.
        /// </summary>
        public static string ClearCanvasText {
            get {
                return ResourceManager.GetString("ClearCanvasText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close the data window (CDTabla).
        /// </summary>
        public static string CloseCDText {
            get {
                return ResourceManager.GetString("CloseCDText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONFIGURATION.
        /// </summary>
        public static string ConfigText {
            get {
                return ResourceManager.GetString("ConfigText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DATE.
        /// </summary>
        public static string DateText {
            get {
                return ResourceManager.GetString("DateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Draw a pie chart.
        /// </summary>
        public static string DrawCircularText {
            get {
                return ResourceManager.GetString("DrawCircularText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Draw a comparative chart.
        /// </summary>
        public static string DrawComparativeText {
            get {
                return ResourceManager.GetString("DrawComparativeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Draw bar chart.
        /// </summary>
        public static string DrawNormalText {
            get {
                return ResourceManager.GetString("DrawNormalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Draw Pactometer.
        /// </summary>
        public static string DrawPactometerText {
            get {
                return ResourceManager.GetString("DrawPactometerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Draw chart.
        /// </summary>
        public static string DrawText {
            get {
                return ResourceManager.GetString("DrawText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ELECTION.
        /// </summary>
        public static string ElectionText {
            get {
                return ResourceManager.GetString("ElectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit the application.
        /// </summary>
        public static string ExitAppText {
            get {
                return ResourceManager.GetString("ExitAppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit the secondary windows.
        /// </summary>
        public static string ExitCDText {
            get {
                return ResourceManager.GetString("ExitCDText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EXIT.
        /// </summary>
        public static string ExitText {
            get {
                return ResourceManager.GetString("ExitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Export chart as image.
        /// </summary>
        public static string ExportText {
            get {
                return ResourceManager.GetString("ExportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register of process (USED).
        /// </summary>
        public static string HistorialText {
            get {
                return ResourceManager.GetString("HistorialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a START.
        /// </summary>
        public static string InitiateText {
            get {
                return ResourceManager.GetString("InitiateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a _jpg.
        /// </summary>
        public static string JPGExportText {
            get {
                return ResourceManager.GetString("JPGExportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register of process (USED).
        /// </summary>
        public static string LanguageText {
            get {
                return ResourceManager.GetString("LanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register of process (USED).
        /// </summary>
        public static string LanguageText1 {
            get {
                return ResourceManager.GetString("LanguageText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logo.
        /// </summary>
        public static string LogoText {
            get {
                return ResourceManager.GetString("LogoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify date.
        /// </summary>
        public static string ModifyDateText {
            get {
                return ResourceManager.GetString("ModifyDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify absolute majority.
        /// </summary>
        public static string ModifyMajorityText {
            get {
                return ResourceManager.GetString("ModifyMajorityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify name.
        /// </summary>
        public static string ModifyNameText {
            get {
                return ResourceManager.GetString("ModifyNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify party list.
        /// </summary>
        public static string ModifyPartText {
            get {
                return ResourceManager.GetString("ModifyPartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify electoral process.
        /// </summary>
        public static string ModifyProcessText {
            get {
                return ResourceManager.GetString("ModifyProcessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify seats.
        /// </summary>
        public static string ModifySeatText {
            get {
                return ResourceManager.GetString("ModifySeatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open help document.
        /// </summary>
        public static string OpenAidText {
            get {
                return ResourceManager.GetString("OpenAidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open secondary window (CDTabla).
        /// </summary>
        public static string OpenCDText {
            get {
                return ResourceManager.GetString("OpenCDText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open configuration window.
        /// </summary>
        public static string OpenConfigText {
            get {
                return ResourceManager.GetString("OpenConfigText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Options.
        /// </summary>
        public static string OptionsButtonText {
            get {
                return ResourceManager.GetString("OptionsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NUMBER OF SEATS.
        /// </summary>
        public static string ParliamentarySeatsText {
            get {
                return ResourceManager.GetString("ParliamentarySeatsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Party.
        /// </summary>
        public static string PartyText {
            get {
                return ResourceManager.GetString("PartyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a _png.
        /// </summary>
        public static string PNGExportText {
            get {
                return ResourceManager.GetString("PNGExportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove electoral process.
        /// </summary>
        public static string RemoveProcessText {
            get {
                return ResourceManager.GetString("RemoveProcessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seats.
        /// </summary>
        public static string SeatsText {
            get {
                return ResourceManager.GetString("SeatsText", resourceCulture);
            }
        }
    }
}
